services:
  resilmesh-ap-misp-client:
    hostname: "misp_client"
    restart: unless-stopped
    env_file:
      - ".env"
    build:
      context: "./"
    deploy:
      replicas: 2
    networks:
      resilmesh_network:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: ["resilmesh-ap-nats", "resilmesh-tap-misp-core"]